context("IGL copula is obtained from IG with theta = Inf")

test_that("IGL copula is obtained from IG with theta = Inf", {
  expect_equal(pigl(.u, .v, 1), pig(.u, .v, c(Inf, 1)))
  expect_equal(digl(.u, .v, 1), dig(.u, .v, c(Inf, 1)))
  expect_equal(pcondigl21(.u, .v, 1), pcondig21(.u, .v, c(Inf, 1)))
  expect_equal(qcondigl21(.u, .v, 1), qcondig21(.u, .v, c(Inf, 1)))
  expect_equal(pcondigl12(.u, .v, 1), pcondig12(.u, .v, c(Inf, 1)))
  expect_equal(qcondigl12(.u, .v, 1), qcondig12(.u, .v, c(Inf, 1)))
  set.seed(1)
  a <- rigl(10, 1)
  set.seed(1)
  b <- rig(10, c(Inf, 1))
  expect_equal(a, b)
})
