---
title: "Investigate why qcondigcop is not always accurate"
output: html_document
---

```{r}
library(tidyverse)
library(igcop)
```

`qcondigcop()` seems to present inaccuracies when tau = 0.8 and (u = 0.2), and a variety of cpar values -- including combinations of $\theta \in \{75, 155, 300, 600\}$ and $k \in \{4, 8, 15, 35\}$.

```{r}
pcondigcop_v2 <- function(v, u, cpar) {
  theta <- cpar[1]
  k <- cpar[2]
  Hkinv <- interp_gen_inv(1 - v, theta, k)
  arg <- theta * (1 - u) * log(Hkinv)
  1 - igamma(k - 1, theta * (1 - u) * log(Hkinv)) / Hkinv / gamma(k - 1)
}
diff <- function(u) pcondigcop(u^2, u, c(75, 8)) - pcondigcop_v2(u^2, u, c(75, 8))
curve(diff)
```


How about qcondigcop?

```{r}
qcondigcop_algo_v2 <- function(p, u, cpar, mxiter = 10000, eps = 1e-8) {
  if (length(p) != 1L) stop("Algorithm requires a single `p`.")
  if (length(u) != 1L) stop("Algorithm requires a single `u`.")
  v <- 0.5
  iter <- 0
  diff <- 0.25
  while (iter < mxiter & abs(diff) > eps) {
    g <- pcondigcop(v, u, cpar) - p
    gp <- digcop(u, v, cpar)
    diff <- g / gp
    if (v - diff < 0) diff <- v / 2
    if (v - diff > 1) diff <-  - (1 - v) / 2
    v <- v - diff
    iter <- iter + 1
    #cat(iter,diff,x,"\n")
  }
  v
}
qcondigcop_v2 <- function(p, u, cpar, mxiter = 80, eps = 1.e-12) {
  lengths <- c(p = length(p), u = length(u))
  l <- max(lengths)
  if (lengths[["p"]] == 1) p <- rep(p, l)
  if (lengths[["u"]] == 1) u <- rep(u, l)
  v <- numeric()
  for (i in 1:l) {
    v[i] <- qcondigcop_algo_v2(
      p[i], u[i], cpar = cpar, mxiter = mxiter, eps = eps
    )
  }
  v
}
cpar <- c(75, 8)
diff <- function(w) qcondigcop_v2(w, w, cpar) - qcondigcop(w, w, cpar)
curve(diff)
```



Try digcop. It appears to be OK, but perhaps with a little more error than the others. 

```{r}
digcop_v2 <- function(u, v, cpar) {
  theta <- cpar[1]
  k <- cpar[2]
  t <- interp_gen_inv(1 - v, theta, k)
  D1Hk <- interp_gen_D1(t, theta, k)
  - (theta ^ (k - 1) * (1 - u) ^ (k - 1) * log(t) ^ (k - 2) * t ^ (-theta * (1 - u)) + 
       igamma(k - 1, theta * (1 - u) * log(t))) / gamma(k - 1) / t ^ 2 / D1Hk
}
cpar <- c(75, 8)
diff <- function(u) digcop_v2(u, u^2, cpar) - digcop(u, u^2, cpar)
curve(diff)
```

