# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dig_vec <- function(u, v, theta, alpha) {
    .Call(`_igcop_dig_vec`, u, v, theta, alpha)
}

igl_gen_vec <- function(x, alpha) {
    .Call(`_igcop_igl_gen_vec`, x, alpha)
}

igl_gen_D_vec <- function(x, alpha) {
    .Call(`_igcop_igl_gen_D_vec`, x, alpha)
}

igl_gen_inv_vec <- function(p, alpha, mxiter, eps, bd) {
    .Call(`_igcop_igl_gen_inv_vec`, p, alpha, mxiter, eps, bd)
}

#' Functions generating the IG and IGL copulas
#'
#' Kappa function and its relatives have prefix `igl_kappa`;
#' Psi function and its relatives have prefix `igl_gen`;
#' Interpolating function H with either kappa or psi has
#' `igl` prefix replaced with `interp`. Relatives of these functions:
#' suffix `inv` indicates inverse; suffix `D` represents function
#' derivative, and `D1` derivative with respect to the first argument.
#'. Suffix `_vec` indicates that the entries must be vectors of
#' the same length; `_single` means entries must be
#' scalars.
#' @param x Function argument
#' @param p Inverse function argument
#' @param eta,alpha Function parameters
igl_kappa_vec <- function(x, alpha) {
    .Call(`_igcop_igl_kappa_vec`, x, alpha)
}

igl_kappa_D_vec <- function(x, alpha) {
    .Call(`_igcop_igl_kappa_D_vec`, x, alpha)
}

igl_kappa_inv_vec <- function(p, alpha) {
    .Call(`_igcop_igl_kappa_inv_vec`, p, alpha)
}

interp_gen_vec <- function(x, eta, alpha) {
    .Call(`_igcop_interp_gen_vec`, x, eta, alpha)
}

interp_gen_D1_vec <- function(x, eta, alpha) {
    .Call(`_igcop_interp_gen_D1_vec`, x, eta, alpha)
}

interp_gen_inv_vec <- function(p, eta, alpha, mxiter, eps, bd) {
    .Call(`_igcop_interp_gen_inv_vec`, p, eta, alpha, mxiter, eps, bd)
}

interp_kappa_vec <- function(x, eta, alpha) {
    .Call(`_igcop_interp_kappa_vec`, x, eta, alpha)
}

interp_kappa_D1_vec <- function(x, eta, alpha) {
    .Call(`_igcop_interp_kappa_D1_vec`, x, eta, alpha)
}

interp_kappa_inv_vec <- function(p, eta, alpha, mxiter, eps, bd) {
    .Call(`_igcop_interp_kappa_inv_vec`, p, eta, alpha, mxiter, eps, bd)
}

pcondig12_vec <- function(u, v, theta, alpha) {
    .Call(`_igcop_pcondig12_vec`, u, v, theta, alpha)
}

qcondig12_vec <- function(p, v, theta, alpha, mxiter, eps, bd) {
    .Call(`_igcop_qcondig12_vec`, p, v, theta, alpha, mxiter, eps, bd)
}

