# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Generating function for the IGL copula family
#'
#' \code{igl_gen} is the function itself, and \code{igl_gen_inv} is
#' its inverse; \code{igl_gen_D} is the
#' derivative; and \code{igl_gen_DD} is the second derivative.
#'
#' Function arguments and parameters are vectorized, except
#' for the algorithms (marked by `_algo`).
#'
#' @param x Vector of values >=0 to evaluate the function at, .
#' @param p Vector of values to evaluate the inverse function at, between
#' 0 and 1 (inclusive).
#' @param alpha Parameter of the function, alpha > 0. Vectorized.
#' @examples
#' ## Some examples of evaluating the functions.
#' arg <- c(0, 0.5, 3, Inf, NA)
#' #igl_gen(arg, alpha = 1)
#' #igl_gen_D(arg, alpha = 0.2)
#' #igl_gen_D(arg, alpha = 1)
#' #igl_gen_D(arg, alpha = 2)
#' #igl_gen_inv(c(0, 0.5, 1), alpha = 0.5)
#'
#' ## Visual
#' #foo <- function(u) igl_gen_inv(u, alpha = 0.5)
#' #curve(foo)
#' @rdname igl_gen
NULL

#' @rdname igl_gen
NULL

#' @param mxiter Maximum number of iterations to run the Newton-Raphson
#' algorithm when computing inverse. Positive integer, default 20
#' (which is used in the calling routine).
#' @param eps The Newton-Raphson algorithm for computing an inverse will
#' stop if the step size is less than this small number. 1.e-12 used
#' in the calling routine.
#' @param bd The largest acceptable step size in the Newton-Raphson
#' algorithm. Step size is reduced if it reaches this large. `bd=5` in
#' the calling routine.
#' @rdname igl_gen
NULL

#' Interpolating Functions
#'
#' These interpolating functions, denoted \eqn{H} in the vignette,
#' depend on a generating function (of a DJ copula).
#' `interp_gen()` uses the IGL generating function \eqn{\Psi_k};
#' `interp_kappa()` uses the "kappa version" of that same function.
#'
#' Appending `_inv` to the function name indicates inverse with
#' respect to the first argument. Appending `_D1` indicates
#' derivative with respect to the first argument. Function arguments
#' and parameters are vectorized, except for the algorithms (marked by
#' `_algo`).
#'
#' @param x Vector of values >=1 to evaluate the interpolating function at.
#' @param p Vector of values between 0 and 1 to evaluate the inverse function at.
#' @param eta Vector of values >0 of second argument of the
#' interpolating function.
#' @param alpha Vector of values >0 corresponding to the \eqn{alpha} parameter
#' of the IGL generating function.
#' @rdname interpolator
NULL

#' @rdname interpolator
NULL

#' @inheritParams igl_gen_inv_algo
#' @rdname interpolator
NULL

